### ISSUE TITLE
TypeError exception with latest version and Python 3

### ISSUE THREAD

**Issue by benoit-pierre** [ColinDuquesnoy/pyqt_distutils#7]
Using Python 3.4:
```
pyrcc5  Z:\home\bpierre\progs\src\plover\plover/gui_qt/resources\resources.qrc -o Z:\home\bpierre\progs\src\plover\plover/gui_qt\resources_rc.py
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pyqt_distutils\build_ui.py", line 93, in run
    subprocess.check_output(cmd.split(' '))
  File "C:\Python34\lib\subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['pyrcc5', '', 'Z:\\home\\bpierre\\progs\\src\\plover\\plover/gui_qt/resources\\resources.qrc', '-o', 'Z:\\home\\bpierre\\progs\\src\\plover\\plover/gui_qt\\resources_rc.py']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 425, in <module>
    **kwargs
  File "C:\Python34\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Python34\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 81, in run
    self.run_command("build")
  File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python34\lib\distutils\command\build.py", line 126, in run
    self.run_command(cmd_name)
  File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 351, in run
    self.run_command(command)
  File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Python34\lib\site-packages\pyqt_distutils\build_ui.py", line 96, in run
    write_message(e.output, 'red')
  File "C:\Python34\lib\site-packages\pyqt_distutils\utils.py", line 18, in write_message
    print(colors[color] + text + colorama.Fore.RESET)
TypeError: Can't convert 'bytes' object to str implicitly
```

**Comment by ColinDuquesnoy** [comment]
Should be fixed in latest commit on master branch. Let me know if that works for you, I'll make a release on pypi.

**Comment by benoit-pierre** [comment]
Works fine, thanks. :+1:

**Comment by ColinDuquesnoy** [comment]
Great! New version has been released on pypi. Thank you for reporting :+1:
